laptop_ip: "100.72.4.68"
log_dir: "/home/ubuntu/stream_logs"
record_dir: "/home/ubuntu/stream_records"

ir_camera:
  device: "/dev/video0"
  width: 640
  height: 512
  framerate: "60/1"
  bitrate: 2000
  video_format: "I420"
  stream: False
  record: False
  display: False

pi_camera:
  width: 640
  height: 480
  framerate: "30/1"
  bitrate: 2500
  video_format: "i420"
  stream: True
  record: False
  display: False

compose:
  enabled: false
  overlay_text: "FPV Demo"
  hdmi: true
  record: false
  stream: false